"""
DecisionMesh — Counterfactual model.
A simulated alternative outcome generated by the Causal Inference Agent.
"""
import json
import uuid
from datetime import datetime

from pydantic import BaseModel, Field
from sqlalchemy import DateTime, Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from decisionmesh.database import Base


# ── Pydantic model ────────────────────────────────────────────────────────────

class Counterfactual(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    decision_id: str
    divergence_event_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    alternative_scenario: str       # "If you had decided X instead..."
    projected_outcome_delta: str    # What would likely be different now
    confidence: float               # 0.0-1.0
    causal_chain: list[str]        # Step-by-step causal reasoning (KNOWN/INFERRED/SPECULATED)
    agent_reasoning: str           # Full extended think output

    model_config = {"from_attributes": True}


# ── SQLAlchemy ORM model ──────────────────────────────────────────────────────

class CounterfactualORM(Base):
    __tablename__ = "counterfactuals"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    decision_id: Mapped[str] = mapped_column(String(36), ForeignKey("decisions.id"), nullable=False)
    divergence_event_id: Mapped[str] = mapped_column(String(36), ForeignKey("divergence_events.id"), nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    alternative_scenario: Mapped[str] = mapped_column(Text, nullable=False)
    projected_outcome_delta: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    causal_chain: Mapped[str] = mapped_column(JSON, nullable=False)
    agent_reasoning: Mapped[str] = mapped_column(Text, nullable=False)

    # Relationships
    decision: Mapped["DecisionORM"] = relationship("DecisionORM", back_populates="counterfactuals_rel")  # noqa: F821
    divergence_event: Mapped["DivergenceEventORM"] = relationship("DivergenceEventORM", back_populates="counterfactuals")  # noqa: F821

    def to_pydantic(self) -> Counterfactual:
        return Counterfactual(
            id=self.id,
            decision_id=self.decision_id,
            divergence_event_id=self.divergence_event_id,
            generated_at=self.generated_at,
            alternative_scenario=self.alternative_scenario,
            projected_outcome_delta=self.projected_outcome_delta,
            confidence=self.confidence,
            causal_chain=self.causal_chain if isinstance(self.causal_chain, list) else json.loads(self.causal_chain),
            agent_reasoning=self.agent_reasoning,
        )
