"""
DecisionMesh — Database CRUD Tools
Tool schemas and implementations for agent DB access.
All inputs are Pydantic-validated.
"""
from typing import Optional
from pydantic import BaseModel, Field


# ── Tool Schemas ──────────────────────────────────────────────────────────────

class GetDecisionInput(BaseModel):
    decision_id: str = Field(description="The UUID of the decision to retrieve.")


class GetPremisesInput(BaseModel):
    decision_id: str = Field(description="The UUID of the decision whose premises to retrieve.")


class GetPriorObservationsInput(BaseModel):
    premise_id: str = Field(description="The UUID of the premise.")
    limit: int = Field(default=5, ge=1, le=50, description="Maximum number of prior observations to return.")


class SaveObservationInput(BaseModel):
    decision_id: str
    premise_id: str
    observation_text: str = Field(description="What the agent found when checking this premise.")
    source_urls: list[str] = Field(default_factory=list)
    relevance_score: float = Field(ge=0.0, le=1.0, description="How relevant this observation is to the premise.")
    supports_premise: Optional[bool] = Field(default=None, description="True=supports, False=contradicts, None=ambiguous.")
    agent_reasoning: str = Field(description="Full think-tool reasoning that led to this observation.")


class ComputeDivergenceInput(BaseModel):
    decision_id: str = Field(description="The decision to compute divergence score for.")


class CreateDivergenceEventInput(BaseModel):
    decision_id: str
    severity: str = Field(description="low|medium|high|critical")
    affected_premise_ids: list[str]
    summary: str = Field(description="Human-readable divergence description.")
    evidence: list[str] = Field(description="Supporting observations as text snippets.")
    divergence_score: float = Field(ge=0.0, le=1.0)


class GetAllActiveDecisionsInput(BaseModel):
    limit: int = Field(default=50, ge=1, le=200)


class SaveCounterfactualInput(BaseModel):
    decision_id: str
    divergence_event_id: str
    alternative_scenario: str
    projected_outcome_delta: str
    confidence: float = Field(ge=0.0, le=1.0)
    causal_chain: list[str] = Field(description="Step-by-step causal reasoning, each labeled KNOWN/INFERRED/SPECULATED.")
    agent_reasoning: str


class UpdateDecisionDNAInput(BaseModel):
    decision_id: str
    field: str = Field(description="Field to update: premises|predicted_outcomes|triggering_conditions|status|domain|tags")
    value: str = Field(description="New value as JSON string for list fields, or plain string for string fields.")


class CloseDecisionInput(BaseModel):
    decision_id: str
    reason: str = Field(description="Why the decision is being closed.")


class PauseMonitoringInput(BaseModel):
    decision_id: str
    pause: bool = Field(description="True to pause, False to resume monitoring.")


# ── Tool Definitions ──────────────────────────────────────────────────────────

GET_DECISION_TOOL: dict = {
    "name": "get_decision_with_premises",
    "description": "Retrieve a decision and all its premises from the database.",
    "input_schema": GetDecisionInput.model_json_schema(),
}

GET_PREMISES_TOOL: dict = {
    "name": "get_premises",
    "description": "Retrieve all premises for a given decision.",
    "input_schema": GetPremisesInput.model_json_schema(),
}

GET_PRIOR_OBSERVATIONS_TOOL: dict = {
    "name": "get_prior_observations",
    "description": "Retrieve the N most recent observations for a specific premise.",
    "input_schema": GetPriorObservationsInput.model_json_schema(),
}

SAVE_OBSERVATION_TOOL: dict = {
    "name": "save_observation",
    "description": "Persist an observation about a premise's current status to the database.",
    "input_schema": SaveObservationInput.model_json_schema(),
}

COMPUTE_DIVERGENCE_TOOL: dict = {
    "name": "compute_divergence_score",
    "description": (
        "Compute the weighted divergence score across all premises for a decision. "
        "Formula: Σ(weight_i × invalidation_score_i) / Σ(weight_i) "
        "where invalidation_score: valid=0.0, uncertain=0.4, invalidated=1.0."
    ),
    "input_schema": ComputeDivergenceInput.model_json_schema(),
}

CREATE_DIVERGENCE_EVENT_TOOL: dict = {
    "name": "create_divergence_event",
    "description": "Create and persist a divergence event when the divergence threshold is exceeded.",
    "input_schema": CreateDivergenceEventInput.model_json_schema(),
}

GET_ALL_ACTIVE_DECISIONS_TOOL: dict = {
    "name": "get_all_active_decisions",
    "description": "Retrieve all active decisions for compounding risk analysis.",
    "input_schema": GetAllActiveDecisionsInput.model_json_schema(),
}

SAVE_COUNTERFACTUAL_TOOL: dict = {
    "name": "save_counterfactual",
    "description": "Persist a counterfactual scenario generated by the Causal Inference Agent.",
    "input_schema": SaveCounterfactualInput.model_json_schema(),
}

UPDATE_DECISION_DNA_TOOL: dict = {
    "name": "update_decision_dna",
    "description": "Update a field in the Decision DNA (premises, outcomes, status, etc.).",
    "input_schema": UpdateDecisionDNAInput.model_json_schema(),
}

CLOSE_DECISION_TOOL: dict = {
    "name": "close_decision",
    "description": "Mark a decision as closed — end of its lifecycle.",
    "input_schema": CloseDecisionInput.model_json_schema(),
}

PAUSE_MONITORING_TOOL: dict = {
    "name": "pause_monitoring",
    "description": "Pause or resume monitoring for a decision.",
    "input_schema": PauseMonitoringInput.model_json_schema(),
}


# ── Tool Execution Functions ──────────────────────────────────────────────────
# These are called by agents during their tool-use loops.

async def db_get_decision(decision_id: str, db_session) -> dict:
    """Fetch decision with premises from DB."""
    from sqlalchemy import select
    from decisionmesh.models.decision import DecisionORM
    from decisionmesh.models.premise import PremiseORM

    result = await db_session.execute(
        select(DecisionORM).where(DecisionORM.id == decision_id)
    )
    decision = result.scalar_one_or_none()
    if not decision:
        return {"error": f"Decision {decision_id} not found"}

    premises_result = await db_session.execute(
        select(PremiseORM).where(PremiseORM.decision_id == decision_id)
    )
    premises = premises_result.scalars().all()

    d = decision.to_pydantic().model_dump(mode="json")
    d["premises_detail"] = [p.to_pydantic().model_dump(mode="json") for p in premises]
    return d


async def db_get_premises(decision_id: str, db_session) -> list[dict]:
    from sqlalchemy import select
    from decisionmesh.models.premise import PremiseORM

    result = await db_session.execute(
        select(PremiseORM).where(PremiseORM.decision_id == decision_id)
    )
    return [p.to_pydantic().model_dump(mode="json") for p in result.scalars().all()]


async def db_get_prior_observations(premise_id: str, limit: int, db_session) -> list[dict]:
    from sqlalchemy import select, desc
    from decisionmesh.models.observation import ObservationORM

    result = await db_session.execute(
        select(ObservationORM)
        .where(ObservationORM.premise_id == premise_id)
        .order_by(desc(ObservationORM.observed_at))
        .limit(limit)
    )
    return [o.to_pydantic().model_dump(mode="json") for o in result.scalars().all()]


async def db_save_observation(data: SaveObservationInput, db_session) -> dict:
    from decisionmesh.models.observation import ObservationORM

    obs = ObservationORM(
        decision_id=data.decision_id,
        premise_id=data.premise_id,
        observation_text=data.observation_text,
        source_urls=data.source_urls,
        relevance_score=data.relevance_score,
        supports_premise=data.supports_premise,
        agent_reasoning=data.agent_reasoning,
    )
    db_session.add(obs)
    await db_session.flush()
    return {"id": obs.id, "status": "saved"}


async def db_compute_divergence(decision_id: str, db_session) -> dict:
    from sqlalchemy import select
    from decisionmesh.models.premise import PremiseORM, PremiseStatus

    result = await db_session.execute(
        select(PremiseORM).where(PremiseORM.decision_id == decision_id)
    )
    premises = result.scalars().all()

    if not premises:
        return {"divergence_score": 0.0, "details": []}

    score_map = {
        PremiseStatus.VALID.value: 0.0,
        PremiseStatus.UNCERTAIN.value: 0.4,
        PremiseStatus.INVALIDATED.value: 1.0,
        PremiseStatus.UNVERIFIABLE.value: 0.2,
    }

    weighted_sum = 0.0
    total_weight = 0.0
    details = []
    for p in premises:
        invalidation_score = score_map.get(p.status, 0.0)
        weighted_sum += p.weight * invalidation_score
        total_weight += p.weight
        details.append({
            "premise_id": p.id,
            "text": p.text[:100],
            "status": p.status,
            "weight": p.weight,
            "invalidation_score": invalidation_score,
        })

    divergence_score = weighted_sum / total_weight if total_weight > 0 else 0.0
    return {"divergence_score": round(divergence_score, 4), "details": details}


async def db_create_divergence_event(data: CreateDivergenceEventInput, db_session) -> dict:
    from decisionmesh.models.divergence import DivergenceEventORM
    from decisionmesh.models.decision import DecisionORM, DecisionStatus

    event = DivergenceEventORM(
        decision_id=data.decision_id,
        severity=data.severity,
        affected_premise_ids=data.affected_premise_ids,
        summary=data.summary,
        evidence=data.evidence,
        divergence_score=data.divergence_score,
    )
    db_session.add(event)

    # Update decision status
    result = await db_session.execute(
        __import__("sqlalchemy", fromlist=["select"]).select(DecisionORM).where(DecisionORM.id == data.decision_id)
    )
    decision = result.scalar_one_or_none()
    if decision:
        decision.status = DecisionStatus.DRIFTED.value

    await db_session.flush()
    return {"divergence_event_id": event.id, "status": "created"}


async def db_get_all_active_decisions(limit: int, db_session) -> list[dict]:
    from sqlalchemy import select
    from decisionmesh.models.decision import DecisionORM, DecisionStatus

    result = await db_session.execute(
        select(DecisionORM)
        .where(DecisionORM.status == DecisionStatus.ACTIVE.value)
        .limit(limit)
    )
    return [d.to_pydantic().model_dump(mode="json") for d in result.scalars().all()]


async def db_save_counterfactual(data: SaveCounterfactualInput, db_session) -> dict:
    from decisionmesh.models.counterfactual import CounterfactualORM

    cf = CounterfactualORM(
        decision_id=data.decision_id,
        divergence_event_id=data.divergence_event_id,
        alternative_scenario=data.alternative_scenario,
        projected_outcome_delta=data.projected_outcome_delta,
        confidence=data.confidence,
        causal_chain=data.causal_chain,
        agent_reasoning=data.agent_reasoning,
    )
    db_session.add(cf)
    await db_session.flush()
    return {"counterfactual_id": cf.id, "status": "saved"}
